# Generated by Django 4.2.2 on 2023-06-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_entry', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doate_of_birth',
            field=models.DateField(null=True),
        ),
    ]
